"use server";

import { PrismaClient, Prisma } from '@prisma/client';
import { revalidatePath } from 'next/cache';
import { auth } from '@clerk/nextjs/server';
import { Lead, SessionData, PipelineStage } from '@/types';

// ─── Prisma Singleton (prevents connection exhaustion in serverless) ──
const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };
const prisma = globalForPrisma.prisma || new PrismaClient();
globalForPrisma.prisma = prisma;

// ─── Auth guard helper ───────────────────────────────────────────────
async function requireAuth(): Promise<string> {
    const { userId } = await auth();
    if (!userId) throw new Error('Unauthorized — sign in required');
    return userId;
}

// Scopes queries to current user + unclaimed leads (migration compat)
function userScope(userId: string): Prisma.LeadWhereInput {
    return { OR: [{ userId }, { userId: null }] };
}

// ─── Input sanitization ──────────────────────────────────────────────
function sanitize(input: string, maxLen = 500): string {
    return input.trim().slice(0, maxLen);
}

function validateEmail(email: string): boolean {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && email.length <= 254;
}

function validateRevenue(revenue: number): boolean {
    return Number.isFinite(revenue) && revenue >= 0 && revenue <= 999_999_999;
}

// Omit ID and Timestamp as they are generated by DB
export type CreateLeadData = Omit<Lead, 'id' | 'timestamp' | 'actions' | 'logs'> & {
    session?: SessionData;
};

export async function createLead(data: CreateLeadData) {
    try {
        const userId = await requireAuth();

        // Input validation
        if (!data.email || !validateEmail(data.email)) {
            return { success: false, error: 'Invalid email address' };
        }
        if (!data.businessName || data.businessName.trim().length < 1) {
            return { success: false, error: 'Business name is required' };
        }
        if (!validateRevenue(data.revenue)) {
            return { success: false, error: 'Invalid revenue amount' };
        }

        const lead = await prisma.lead.create({
            data: {
                userId,
                email: sanitize(data.email, 254),
                phone: sanitize(data.phone, 20),
                revenue: data.revenue,
                businessName: sanitize(data.businessName, 200),
                tier: data.tier,
                temperature: data.temperature,
                score: Math.max(0, Math.min(100, data.score)),
                dncStatus: data.dncStatus,
                pipelineStage: data.pipelineStage || 'New',
                state: data.state ? sanitize(data.state, 50) : null,
                session: data.session ? JSON.stringify(data.session) : null,
                actions: {
                    create: {
                        type: 'LEAD_CREATED',
                        status: 'SUCCESS',
                        message: 'Lead created via manual entry'
                    }
                },
                logs: {
                    create: {
                        level: 'INFO',
                        message: 'Lead entered into system',
                        module: 'CORE'
                    }
                }
            }
        });
        revalidatePath('/dashboard');
        revalidatePath('/pipeline');
        return { success: true, lead };
    } catch (error) {
        console.error('Failed to create lead:', error);
        return { success: false, error: 'Failed to create lead' };
    }
}

// ─── BULK INSERT (20K scale) ─────────────────────────────────────────
export type BulkLeadData = {
    email: string;
    phone: string;
    revenue: number;
    businessName: string;
    tier: string;
    temperature: string;
    score: number;
    dncStatus: string;
    pipelineStage?: string;
    state?: string;
    industry?: string;
    contactName?: string;
};

export async function bulkCreateLeads(leads: BulkLeadData[]) {
    try {
        const userId = await requireAuth();

        // Rate-limit: max 1000 leads per bulk import
        if (leads.length > 1000) {
            return { success: false, error: 'Max 1000 leads per import', count: 0 };
        }

        const result = await prisma.$transaction(async (tx) => {
            const created = await tx.lead.createMany({
                data: leads.map(l => ({
                    userId,
                    email: sanitize(l.email, 254),
                    phone: sanitize(l.phone, 20),
                    revenue: Math.max(0, Math.min(999_999_999, l.revenue)),
                    businessName: sanitize(l.businessName, 200),
                    tier: l.tier,
                    temperature: l.temperature,
                    score: Math.max(0, Math.min(100, l.score)),
                    dncStatus: l.dncStatus,
                    pipelineStage: l.pipelineStage || 'New',
                    state: l.state ? sanitize(l.state, 50) : null,
                    industry: l.industry ? sanitize(l.industry, 100) : null,
                    contactName: l.contactName ? sanitize(l.contactName, 200) : null,
                    session: null,
                })),
            });
            return created.count;
        });

        revalidatePath('/dashboard');
        revalidatePath('/pipeline');
        return { success: true, count: result };
    } catch (error) {
        console.error('Bulk insert failed:', error);
        return { success: false, error: 'Bulk insert failed', count: 0 };
    }
}

// ─── PAGINATED FETCH (server-side search/filter) ─────────────────────
export type LeadFilters = {
    search?: string;
    temperature?: string;
    minScore?: number;
    pipelineStage?: string;
};

export async function getLeadsPaginated(
    page: number = 1,
    pageSize: number = 50,
    filters?: LeadFilters
) {
    try {
        const userId = await requireAuth();

        // Enforce max page size to prevent data dump attacks
        const safePage = Math.max(1, Math.floor(page));
        const safePageSize = Math.min(100, Math.max(1, Math.floor(pageSize)));

        const where: Prisma.LeadWhereInput = userScope(userId);

        if (filters?.search) {
            const searchTerm = sanitize(filters.search, 100);
            where.AND = [userScope(userId), {
                OR: [
                    { businessName: { contains: searchTerm, mode: 'insensitive' } },
                    { email: { contains: searchTerm, mode: 'insensitive' } },
                    { state: { contains: searchTerm, mode: 'insensitive' } },
                    { phone: { contains: searchTerm, mode: 'insensitive' } },
                ],
            }];
        }
        if (filters?.temperature && filters.temperature !== 'All') {
            where.temperature = filters.temperature;
        }
        if (filters?.minScore) {
            where.score = { gte: filters.minScore };
        }
        if (filters?.pipelineStage) {
            where.pipelineStage = filters.pipelineStage;
        }

        const [leads, total] = await Promise.all([
            prisma.lead.findMany({
                where,
                orderBy: { timestamp: 'desc' },
                skip: (safePage - 1) * safePageSize,
                take: safePageSize,
            }),
            prisma.lead.count({ where }),
        ]);

        const mappedLeads: Lead[] = leads.map(l => ({
            ...l,
            state: l.state ?? undefined,
            industry: l.industry ?? undefined,
            contactName: l.contactName ?? undefined,
            session: l.session ? JSON.parse(l.session) : undefined,
            actions: [],
            pipelineStage: l.pipelineStage as PipelineStage,
            tier: l.tier as any,
            temperature: l.temperature as any,
            dncStatus: l.dncStatus as any,
            logs: [],
        }));

        return {
            success: true,
            leads: mappedLeads,
            total,
            page: safePage,
            pageSize: safePageSize,
            totalPages: Math.ceil(total / safePageSize),
        };
    } catch (error) {
        console.error('Failed to fetch paginated leads:', error);
        return { success: false, leads: [], total: 0, page: 1, pageSize, totalPages: 0 };
    }
}

// ─── AGGREGATED STATS (no full fetch needed) ─────────────────────────
export async function getLeadStats() {
    try {
        const userId = await requireAuth();

        const [total, hotCount, warmCount, coldCount, avgScore, totalRevenue] = await Promise.all([
            prisma.lead.count({ where: userScope(userId) }),
            prisma.lead.count({ where: { ...userScope(userId), temperature: 'Hot' } }),
            prisma.lead.count({ where: { ...userScope(userId), temperature: 'Warm' } }),
            prisma.lead.count({ where: { ...userScope(userId), temperature: 'Cold' } }),
            prisma.lead.aggregate({ where: userScope(userId), _avg: { score: true } }),
            prisma.lead.aggregate({ where: userScope(userId), _sum: { revenue: true } }),
        ]);

        return {
            success: true,
            stats: {
                total,
                hot: hotCount,
                warm: warmCount,
                cold: coldCount,
                lukewarm: total - hotCount - warmCount - coldCount,
                avgScore: Math.round(avgScore._avg.score || 0),
                totalRevenue: totalRevenue._sum.revenue || 0,
            }
        };
    } catch (error) {
        console.error('Failed to get stats:', error);
        return { success: false, stats: null };
    }
}

// ─── LEGACY (keep for backward compat) ───────────────────────────────
export async function getLeads() {
    try {
        const userId = await requireAuth();

        const prismaLeads = await prisma.lead.findMany({
            where: userScope(userId),
            orderBy: { timestamp: 'desc' },
            include: { logs: true }
        });

        const leads: Lead[] = prismaLeads.map(l => ({
            ...l,
            state: l.state ?? undefined,
            industry: l.industry ?? undefined,
            contactName: l.contactName ?? undefined,
            session: l.session ? JSON.parse(l.session) : undefined,
            actions: [],
            pipelineStage: l.pipelineStage as PipelineStage,
            tier: l.tier as any,
            temperature: l.temperature as any,
            dncStatus: l.dncStatus as any,
            logs: l.logs.map(log => ({
                ...log,
                level: log.level as any,
                module: log.module as any
            }))
        }));

        return { success: true, leads };
    } catch (error) {
        console.error('Failed to fetch leads:', error);
        return { success: false, error: 'Failed to fetch leads' };
    }
}

export async function updateLeadStage(leadId: string, stage: string) {
    try {
        const userId = await requireAuth();

        // Validate stage to prevent injection of arbitrary values
        const validStages = ['New', 'Engagement', 'Proposal', 'Negotiation', 'Closed'];
        if (!validStages.includes(stage)) {
            return { success: false, error: 'Invalid pipeline stage' };
        }

        // Ensure the lead belongs to this user (prevents lateral access)
        const lead = await prisma.lead.findFirst({
            where: { id: leadId, ...userScope(userId) },
        });
        if (!lead) {
            return { success: false, error: 'Lead not found' };
        }

        await prisma.lead.update({
            where: { id: leadId },
            data: {
                pipelineStage: stage,
                logs: {
                    create: {
                        level: 'INFO',
                        message: `Lead moved to ${stage}`,
                        module: 'CORE'
                    }
                }
            }
        });
        revalidatePath('/pipeline');
        revalidatePath('/dashboard');
        return { success: true };
    } catch (error) {
        console.error('Failed to update lead stage:', error);
        return { success: false, error: 'Failed to update lead stage' };
    }
}

// --- RESCORE: Recalculate all leads with unified scoring ---
export async function rescoreAllLeads() {
    const userId = await requireAuth();
    const { calculateTier } = await import('@/utils/ironGateLogic');

    // Only rescore this user's leads
    const leads = await prisma.lead.findMany({
        where: userScope(userId),
        select: { id: true, revenue: true },
    });
    let updated = 0;

    const CHUNK_SIZE = 50;
    for (let i = 0; i < leads.length; i += CHUNK_SIZE) {
        const chunk = leads.slice(i, i + CHUNK_SIZE);
        await prisma.$transaction(
            chunk.map(lead => {
                const { tier, temperature, score } = calculateTier(lead.revenue);
                return prisma.lead.update({
                    where: { id: lead.id },
                    data: { tier, temperature, score },
                });
            })
        );
        updated += chunk.length;
    }

    revalidatePath('/dashboard');
    revalidatePath('/pipeline');
    revalidatePath('/analytics');
    return { updated };
}
